#!/bin/sh

bindir=.

tmp=/tmp/`basename $0`-$$
input=$tmp.wav # no comment support

[ "$SOX_TEST_BINDIR" ] && bindir="$SOX_TEST_BINDIR"

check_file () {
  ${bindir}/soxdbg --i -a $1 > $tmp.comments
  cmp $tmp.comments $2 || exit 1
}

check () {
  f=$1; shift
  : > $tmp.expected
  while [ $# != 0 ]; do
    echo "$1" >> $tmp.expected
    shift
  done
  check_file $f $tmp.expected
}

com0="Processed by SoX"
com1="foo bar"
com2="bar foo"

${bindir}/soxdbg -n $input trim 0 .1

${bindir}/soxdbg $input $tmp.au # Apply default comment
check $tmp.au "$com0"

cp $tmp.au $tmp.comment.au

cat > $tmp.i << .
TITLE=First Track
ARTIST=A Band
ALBUM=A Collection Of Songs
TRACKNUMBER=01
.

${bindir}/soxdbg $input --comment-file $tmp.i $tmp.comments.au
check_file $tmp.comments.au $tmp.i

${bindir}/soxdbg $input --comment= $tmp.au # Don't apply default comment
check $tmp.au

${bindir}/soxdbg $input --add-comment "$com1" $tmp.au
check $tmp.au "$com1"

${bindir}/soxdbg $tmp.comment.au --add-comment "$com1" $tmp.au
check $tmp.au "$com0" "$com1"

${bindir}/soxdbg $input --add-comment "$com1" --add-comment "$com2" $tmp.au
check $tmp.au "$com1" "$com2"

${bindir}/soxdbg $tmp.comment.au --add-comment "$com1" --add-comment "$com2" $tmp.au
check $tmp.au "$com0" "$com1" "$com2"

${bindir}/soxdbg $tmp.comments.au --comment= $tmp.au
check $tmp.au

${bindir}/soxdbg $tmp.comments.au --comment "$com1" $tmp.au
check $tmp.au "$com1"

${bindir}/soxdbg $tmp.comments.au --add-comment "$com1" $tmp.au
cp $tmp.i $tmp.j
echo "$com1" >> $tmp.j
check_file $tmp.au $tmp.j

${bindir}/soxdbg $tmp.comments.au --add-comment "$com1" --add-comment "$com2" $tmp.au
echo "$com2" >> $tmp.j
check_file $tmp.au $tmp.j

# FIXME: smp mp3
${bindir}/soxdbg $tmp.comments.au $tmp.aiff
${bindir}/soxdbg $tmp.aiff $tmp.flac
${bindir}/soxdbg $tmp.flac $tmp.sf
${bindir}/soxdbg $tmp.sf $tmp.ogg
${bindir}/soxdbg $tmp.ogg $tmp.sndt
${bindir}/soxdbg $tmp.sndt $tmp.sox
${bindir}/soxdbg $tmp.sox $tmp.au
check_file $tmp.au $tmp.i

rm -f $tmp.*
exit 0
